### ISSUE TITLE
Tabbar 重影

### ISSUE THREAD

**Issue by gmaukh4517** [LeoiOS/LCTabBarController#11]
你好！
   当调用 popToRootViewControllerAnimated Tabbar出现重新，是应为系统的Item与自定义的Item重叠了

**Comment by iTofu** [comment]
popToRootVC 后需要调一个方法，详见readme

发自我的 iPhone

**Comment by iTofu** [comment]
@gmaukh4517 

在调用 `- popToRootViewController` 方法后，你需要调用以下方法：

``` objc
[lcTabBarController removeOriginControls];
```

详见 [README](https://github.com/iTofu/LCTabBarController/blob/master/README_zh-CN.md) [V 1.2.6](https://github.com/iTofu/LCTabBarController/blob/master/README_zh-CN.md#v-126) 更新。
