### ISSUE TITLE
Items are not visible

### ISSUE THREAD

**Issue by mradzinski** [LeoiOS/LCTabBarController#12]
Description:
I had a UITabBarController in my App which I decided to swap for your LCTabBarController. The UITabBarController **wasn't** being added programmatically, it was added through a Storyboard, so I just changed the Class type in the Storyboard scene.

Expected outcome:
All items are visible like they were when using UITabBarController

Outcome:
Although all items and controllers are present (printing tabBar.items revealed 4 items), none of them is visible nor accessible.

Note:
I find this behaviour pretty weird since in your readme you assure integration should be simply swapping classes...

**Comment by iTofu** [comment]
My fault... It doesn't support Storyboard for the time being...
