### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by sunnysuhappy** [LeoiOS/LCTabBarController#13]
最近客户端报了几个闪退，找不到原因，检查代码发现这个地方很有嫌疑
- (void)removeOriginControls {
  
  [self.tabBar.subviews enumerateObjectsWithOptions:NSEnumerationConcurrent usingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
  
  ```
  if ([obj isKindOfClass:[UIControl class]]) {
  
      [obj removeFromSuperview];
  }
  ```
  
  }];
  }
  这个方法是不是有问题，removeFromSuperview是view操作应该是在主线程操作的，但是NSEnumerationConcurrent又是并发，不全是在主线程

**Comment by iTofu** [comment]
对……我马上改……

**Comment by iTofu** [comment]
由于 CocoaPods 和 Xcode 8 的一些问题，暂时需要这么导入：

``` ruby
pod 'LCTabBarController', :git => 'https://github.com/iTofu/LCTabBarController.git' # Podfile
```

**Comment by iTofu** [comment]
可以直接导入了：

``` ruby
pod 'LCTabBarController'
```
