### ISSUE TITLE
想问下修改tabbar的高度的问题

### ISSUE THREAD

**Issue by YisenEason** [LeoiOS/LCTabBarController#18]
如何修改tabbar的高度，我试过在tabbarcontroller直接修改，然后图标那些都全部偏上面去了.

**Comment by iTofu** [comment]
你可以先看一下 UI 结构：

![](http://ob5ymsmos.bkt.clouddn.com/lctabbarcontrollerdemo.png)
![](http://ob5ymsmos.bkt.clouddn.com/QQ20170322-185425@2x.png)

然后读一下源码改一下。

**Comment by YisenEason** [comment]
好的，谢谢
