### ISSUE TITLE
Landscape mode not working!!!

### ISSUE THREAD

**Issue by satyamub** [LeoiOS/LCTabBarController#2]
I tried the code however the landscape mode is not working. Am I doing anything wrong?

**Comment by iTofu** [comment]
![image](http://7xl8ia.com1.z0.glb.clouddn.com/QQ20151230-2%402x.png)

Maybe it's not so good, but it should be effective...

**Comment by satyamub** [comment]
Its not tilting !!!

**Comment by iTofu** [comment]
![Image](http://7xl8ia.com1.z0.glb.clouddn.com/QQ20160119-0.png)
