### ISSUE TITLE
rootViewController removeOriginControls 崩溃

### ISSUE THREAD

**Issue by SuperSmileForever** [LeoiOS/LCTabBarController#21]
tabar里面的控制器,popToRootViewControllerAnimated 时候removeOriginControls,会崩溃,求原因,
-[UIViewController removeOriginControls]: unrecognized selector sent to instance 0x1022534e0

**Comment by iTofu** [comment]
请注意 `- (void)removeOriginControls;` 是 `LCTabBarController` 的实例方法，从你的 Crash 信息来看是 UIViewController 实例调用了该方法。

```objc
// 在某个 UIViewController 中 pop 到最外层控制器:
[self.navigationController popToRootViewControllerAnimated:YES];

[lcTabBarController removeOriginControls];
```

**Comment by SuperSmileForever** [comment]
[self.navigationController popToRootViewControllerAnimated:YES];
  [(LCTabBarController *)[UIApplication sharedApplication].keyWindow.rootViewController removeOriginControls];这是我的调用方法,VC进来的时候根控制器四LcTabBarController,跳转时候,就不知道为什么变成了UIViewController

(方便的话,加个qq请教一下478940556)

**Comment by iTofu** [comment]
Close because solved.

> http://note.leodev.me/2015/12/29/iOS-How-to-implement-the-UIAlertView-of-the-system/
