### ISSUE TITLE
有时候会出现重影和item 图标和标题从上下布局变成左右布局的问题 

### ISSUE THREAD

**Issue by leonard385** [LeoiOS/LCTabBarController#24]
有时候会出现重影和item 图标和标题从上下布局变成左右布局的问题 。截图传不上来，不知道你们用的时候出现这个问题没？手机从休眠状态到解锁状态容易出现

**Comment by iTofu** [comment]
https://github.com/iTofu/LCTabBarController#v-126
这个问题吗？

**Comment by leonard385** [comment]
感谢，找了好久暂时用系统的代替了。有时候出现的左右布局是什么情况，图片在左文字在右的情况，你有遇到过吗？

**Comment by iTofu** [comment]
没遇到过你描述的情况，你能截张图我看下吗？

**Comment by iTofu** [comment]
已修复，请更新到 [V 1.3.7](https://github.com/iTofu/LCTabBarController/releases/tag/1.3.7) 。

**Comment by leonard385** [comment]
好的，感谢提醒
