### ISSUE TITLE
iOS11会出现系统默认TabBar,导致视觉重影

### ISSUE THREAD

**Issue by Shin1122** [LeoiOS/LCTabBarController#26]
源代码未改动过,在iOS8-10系统运行均没问题,在iOS11系统下直接运行模拟器和真机都会出现该情况.
![img_9e29274fce01-1](https://cloud.githubusercontent.com/assets/19711707/26814562/2416c396-4a4c-11e7-8e19-a7b7280fbb47.jpeg)

**Comment by iTofu** [comment]
抱歉暂未收到 iOS 11 的更新推送，将在收到推送并更新后第一时间修复该问题。

**Comment by soppysonny** [comment]
原因是原生item无法移除, 已经暂时改为KVC替换tabbar的做法了...

**Comment by wengxianxun** [comment]
楼上的怎么做呢，能不能提供下代码看看

**Comment by wengxianxun** [comment]
@iTofu  安装个开发者版测试看看。

**Comment by soppysonny** [comment]
tabbarcontroller里 [self setValue:自定义tabbarr forKey:@"tabBar"];

**Comment by shanxifanliang** [comment]
楼上怎么解决的哦 求demo 看看

**Comment by iTofu** [comment]
已修复，请更新到 [V 1.3.7](https://github.com/iTofu/LCTabBarController/releases/tag/1.3.7) 。
