### ISSUE TITLE
iOS11那个重影还是存在呢。

### ISSUE THREAD

**Issue by wengxianxun** [LeoiOS/LCTabBarController#28]
iOS11那个重影还是存在呢。

**Comment by iTofu** [comment]
...回头我把 iPad 升下 iOS 11 beta 测一下吧，其实适配 beta OS 是件不必要的事... 因为系统的很多地方还没定下来或者是没写好，App 很容易就给 beta 版本背了锅。

**Comment by shanxifanliang** [comment]
正式版iOS也出现重影了，求大佬解决一下～

**Comment by luoei** [comment]
@iTofu  直接用iTunes更新吧，正式版下载地址页面：http://act.feng.com/wetools/index.php?r=iosRom/index

**Comment by Shin1122** [comment]
大佬今晚修复.坐等
![u 480599490 553056366 fm 173 s 2be6722298b10da74b9570c90100a0e1 w 550 h 543 img](https://user-images.githubusercontent.com/19711707/30690643-76d7e1f0-9ef7-11e7-8d0a-b601da3abbc3.jpeg)

**Comment by iTofu** [comment]
已修复，请更新到 [V 1.3.7](https://github.com/iTofu/LCTabBarController/releases/tag/1.3.7) 。
