### ISSUE TITLE
TabBarImage Not changing

### ISSUE THREAD

**Issue by Sesadev** [LeoiOS/LCTabBarController#3]
After doing some event in Any tab except if i am trying to come First tab , its comintg but the tabbar image is not showing select

**Comment by iTofu** [comment]
Do you do this?

``` objc
tabBarController.selectedIndex = 1;
```

Year, it's a bug, I'm fixing this bug now. When it's fixed, I'll tell you right now！

**Comment by iTofu** [comment]
@Sesadev 
Fixed! Just run this command:

``` ruby
pod update --verbose --no-repo-update
```
