### ISSUE TITLE
LCTabBarController问题

### ISSUE THREAD

**Issue by Zohar163** [LeoiOS/LCTabBarController#4]
有点问题想问问：
1、tabBarC.tabBar.backgroundColor = [UIColor yellowColor];好像设置了没有生效；
2、tabBarC.tabBar.selectionIndicatorImage = [UIImage imageNamed:@"tabbaritem_bg"];好像设置了没有生效；
因为有时需求是选中的tabBarItem的背景跟未选中的不一样。有劳了！

**Comment by iTofu** [comment]
README 中应该有这个问题的解决方案：

``` objc
HomeVC *vc1 = [[HomeVC alloc] init];
vc1.view.backgroundColor = [UIColor whiteColor];
vc1.tabBarItem.badgeValue = @"23";
vc1.title = @"Home";

// THIS LINE ⬇️
vc1.tabBarItem.image = [UIImage imageNamed:@"tabbar_home"];
vc1.tabBarItem.selectedImage = [UIImage imageNamed:@"tabbar_home_selected"];
```

**Comment by iTofu** [comment]
如果你想改变 tabbar 整体的背景色，在 LCTabBarController 中的 77~78 行添加代码：

``` objc
tabbar.backgroundColor = colorYouNeed;
```

**Comment by iTofu** [comment]
我 GitHub Desktop 挂掉了，改不了，你自己改改。

**Comment by Zohar163** [comment]
1、LCTabBarController 中的 77~78 行添加代码：tabbar.backgroundColor = [UIColor redColor];有效果；不过这样是直接改你代码，我用背景图片也可以；
2、选中的tabBarItem背景图片能改吗？能改的话怎么改？

**Comment by iTofu** [comment]
要改代码

发自我的 iPhone
